plugins {
    id 'com.android.application'
}

android {
    namespace 'kr.co.office3852.elevatorbid'
    compileSdk 35

    defaultConfig {
        applicationId 'kr.co.office3852.elevatorbid'
        minSdk 24
        targetSdk 35
        versionCode 3
        versionName '2.0'
    }
}

dependencies {
    implementation 'com.google.androidbrowserhelper:androidbrowserhelper:2.5.0'
}
